# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNum', models.CharField(max_length=8, verbose_name='工号')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('phoneNum', models.CharField(max_length=11, verbose_name='联系电话')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('salary', models.IntegerField(verbose_name='工资')),
            ],
        ),
    ]
