# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=8, verbose_name='密码')),
                ('address', models.CharField(max_length=50, verbose_name='收货地址')),
                ('balance', models.IntegerField(verbose_name='余额')),
            ],
        ),
    ]
