# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopNum', models.CharField(default=None, max_length=10, verbose_name='店铺编号')),
                ('img', models.CharField(default='', max_length=50, verbose_name='图片路径')),
                ('msg', models.CharField(max_length=50, verbose_name='评论文字内容')),
                ('starNum', models.IntegerField(verbose_name='评分')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(default=None, max_length=15, verbose_name='订单号')),
                ('name', models.CharField(max_length=15, verbose_name='品名')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('subtotal', models.IntegerField(verbose_name='小计')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(default=None, max_length=15, unique=True, verbose_name='订单号')),
                ('shopNum', models.CharField(max_length=8, verbose_name='商户编号')),
                ('shopName', models.CharField(max_length=15, verbose_name='店铺名称')),
                ('shopPhone', models.CharField(max_length=11, verbose_name='店铺联系电话')),
                ('address0', models.CharField(max_length=50, verbose_name='店铺地址')),
                ('address1', models.CharField(max_length=50, verbose_name='收货地址')),
                ('stuPhone', models.CharField(max_length=11, verbose_name='收货人联系电话')),
                ('note', models.CharField(max_length=30, verbose_name='订单备注')),
                ('total', models.IntegerField(verbose_name='总计')),
                ('status', models.BooleanField(default=False, verbose_name='订单状态')),
            ],
        ),
    ]
