# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNum', models.CharField(max_length=8, verbose_name='工号')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('gender', models.CharField(max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('password', models.CharField(max_length=8, verbose_name='密码')),
            ],
        ),
    ]
