# Generated by Django 5.1.3 on 2024-11-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopNum', models.CharField(default=None, max_length=8, verbose_name='所属商铺编号')),
                ('name', models.CharField(max_length=20, verbose_name='食物名称')),
                ('explain', models.CharField(max_length=35, verbose_name='食物介绍')),
                ('img', models.CharField(default='', max_length=50, verbose_name='图片路径')),
                ('price', models.IntegerField(verbose_name='单价')),
                ('sellOut', models.BooleanField(default=False, verbose_name='是否售罄')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterData', models.DateTimeField(verbose_name='入驻日期')),
                ('shopNum', models.CharField(max_length=8, unique=True, verbose_name='商户编号')),
                ('name', models.CharField(max_length=15, verbose_name='店铺管理者姓名')),
                ('legalPerson', models.CharField(default='', max_length=15, verbose_name='法人姓名')),
                ('phoneNum', models.CharField(max_length=11, verbose_name='联系电话')),
                ('address', models.CharField(max_length=50, verbose_name='店铺地址')),
                ('password', models.CharField(default='', max_length=10, verbose_name='密码')),
                ('img', models.CharField(default='', max_length=50, verbose_name='图片路径')),
                ('sale', models.IntegerField(default=0, verbose_name='每日销售额')),
                ('main', models.IntegerField(default=1, verbose_name='主营')),
            ],
        ),
    ]
